### PR TITLE
Update index.php

### PR DESCRIPTION
**Pull request by McLive**
Flat avatars are now actually working again and 3D-Heads are prettier.

### CODE REVIEW

**Comment by franga2000** [comment]
I'm not using cravatar because it doesn't support hats (many skins look strange withot them). If anyone knows a service that does, please let me know.

**Comment by McLive** [comment]
Sure, it does support hats.

**Comment by franga2000** [comment]
Oh, I see it does. It didn't use to.

**Comment by McLive** [comment]
Well done :+1:

**Comment by franga2000** [comment]
Well done to you. Thanks for the help (I was googling for like half an hour, but I didn't think to check cravatar if they added it)

**Pull request merged**
